---
default_language_version:
  python: python3.12

default_stages: [pre-commit]

repos:
  - repo: local
    hooks:
      - id: ruff-lint
        name: ruff-lint
        language: system
        entry: poetry
        args: [run, ruff, check, --force-exclude, --fix, --exit-non-zero-on-fix]
        types: ["python"]

      - id: ruff-format
        name: ruff-format
        language: system
        entry: poetry
        args: [run, ruff, format, --check]
        types: ["python"]

      - id: chkcsv
        name: chkcsv
        language: system
        entry: poetry
        args: [run, python3, validate_csv.py]
        types: ["csv"]
