[tool.poetry]
name = "boaviztapi"
version = "1.3.4"
description = "An API to access Boavizta's methodologies and footprint reference data"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pydantic = "^2.9.2"
fastapi = "^0.115.0"
uvicorn = "^0.22"
pandas = "^2.0"
aiofile = "^3.8"
numpy = "^1.24"
scipy = "^1.9"
rapidfuzz = "^3.0"
markdown = "^3.4"
mangum = "^0.17"
importlib-metadata = "^6.6.0"
pyyaml = "^6.0"
toml = "^0.10.2"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-asyncio = "^0.24.0"
atomicwrites = "^1.4.1"
httpx = "^0.28.1"
requests = "^2.32.3"

[tool.poetry.group.docs]
optional = true

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.5.3"
mkdocs-material = "^9.4.4"
mkdocs-render-swagger-plugin = "^0.1.0"
mkdocs-macros-plugin = "^1.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
