site_name: Boavizta API documentation
dev_addr: '0.0.0.0:8080'
plugins:
    - render_swagger

markdown_extensions:
    - attr_list
    - md_in_html
      

nav:
    - Introduction: index.md 
    - Getting started:
        - Try the API (OpenAPI): !ENV [API_URL, http://api.boavizta.org:5000/docs]
        - Get the impacts of a server: getting_started/single_server.md
        - Get the impacts of a cloud instance (AWS): getting_started/single_cloud_instance.md

    - Explanations:
        - Boavizta database: Explanations/boavizta-db.md
        - Components: Explanations/component.md
        - Device: Explanations/devices.md
        - Manufacture methodology: Explanations/manufacture_methodology.md
        - Manufacture per components: Explanations/manufacture-components.md
        - Manufacture per devices: Explanations/manufacture_devices.md
        - Usage methodology: Explanations/usage.md
        - Smart complete: Explanations/smart-complete.md
        - Archetypes: Explanations/archetypes.md
        - Verbose: Explanations/verbose.md
        - Useful resources: Explanations/useful_resources.md
    - Reference:
        - Component route: Reference/component_route.md
        - Model: Reference/model.md
        - Configuration: Reference/configuration.md
        - Usage: Reference/usage.md
        - Server route: Reference/server_route.md
        - Cloud route: Reference/cloud_route.md
        - Architecture decisions records (ADRs) :
            - Bottom up methodology: ADR/adr1-Bottom-up.md
            - Always return something: ADR/adr2-Alway-return-something.md    

theme: material